venvfinal/final/Dashboard/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Dashboard.views import DashboardClass


app_name = 'Dashboard'
urlpatterns = [
    path('Dashboard',DashboardClass.as_view(), name = 'Dashboard')
]

venvfinal/final/Landing/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Landing.views import LandingClass



app_name = 'Landing'
urlpatterns = [
    path('',LandingClass.as_view(), name = 'landing'),
]

venvfinal/final/Login/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Login.views import LoginClass


app_name = 'Login'
urlpatterns = [
    path('',LoginClass.as_view(), name = 'Login'),
    # path('Dashboard',DashboardClass.as_view(), name = 'Dashboard')
    
]

venvfinal/final/Registro/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Registro.views import RegistrateView


app_name = 'Registro'
urlpatterns = [
    path('',RegistrateView.as_view(), name = 'Registro')
]

venvfinal/final/final/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path,re_path
from django.contrib.auth.views import logout_then_login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('Landing.urls')),
    path('accounts/login/', include ('Login.urls')),
    path('Dashboard/', include ('Dashboard.urls')),
    path('Registrate/', include ('Registro.urls')),
    path('logout/', logout_then_login, name='logout'),
]

venvfinal/final/Dashboard/models.py
from django.db import models

# Create your models here.

venvfinal/final/Landing/models.py
from django.db import models

# Create your models here.

venvfinal/final/Login/models.py
from django.db import models

# Create your models here.

venvfinal/final/Registro/models.py
from django.db import models

# Create your models here.

venvfinal/final/Registro/forms.py
from django.contrib.auth.models import User
from django import forms

ERROR_MESSAGE_USER = {'unique' : 'El Username ya se encuentra registrado', 'invalid' : 'usuario o contraseña incorrecto'}
ERROR_MESSAGE_PASSWORD = {'required' : 'El password es requerido'}
ERROR_MESSAGE_EMAIL = {'invalid' : 'Ingrese un correo valido'}
ERROR_MESSAGE_PHONE = {'invalid' : 'Formato numero incorrecto'}


class RegisterBusinessForm(forms.ModelForm):
    first_name = forms.CharField(label='', required=True)
    last_name = forms.CharField(label='', required=True)
    password = forms.CharField(max_length = 20,required=True, widget = forms.PasswordInput(), error_messages = ERROR_MESSAGE_PASSWORD )
    email = forms.CharField( required = True, error_messages = ERROR_MESSAGE_EMAIL)

    def __init__(self, *args, **kwargs):
        super(RegisterBusinessForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update( {'id': 'username_create', 'class': 'form-control', 'placeholder': 'usuario'} ) # Esto es un input en HTML <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name = "password" required>
        self.fields['first_name'].widget.attrs.update( {'id': 'first_name_create', 'class': 'form-control', 'placeholder': 'Nombre'} )
        self.fields['last_name'].widget.attrs.update( {'id': 'last_name_create', 'class': 'form-control', 'placeholder': 'Apellidos'} )
        self.fields['password'].widget.attrs.update( {'id': 'password_create', 'class': 'form-control', 'placeholder': 'Contraseña'} )
        self.fields['email'].widget.attrs.update( {'id': 'email_create', 'class': 'form-control', 'placeholder': 'Correo Electrónico'} )

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']

venvfinal/final/Dashboard/views.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import redirect
from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

class DashboardClass(LoginRequiredMixin,View):
    templates_m = 'Dashboard/Dashboard.html'

    def get (self,request,*args,**kwargs):
        return render(request,self.templates_m,{})

    

venvfinal/final/Landing/views.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import redirect
from django.contrib.auth import authenticate

class LandingClass(View):
    templates_ok = 'Landing/Landing.html'
    def get(self, request, *args, **kwargs):
        return render(request,self.templates_ok,{})

venvfinal/final/Login/views.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import redirect
from django.contrib.auth import authenticate

from django.contrib.auth import login as login_django


class LoginClass(View):
    templates = 'Login/Login.html'
    templates_ok = 'Landing/Landing.html'
    def get(self, request, *args, **kwargs):
        
        if request.user.is_authenticated:
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('Dashboard:Dashboard')
        return render(request, self.templates,{})


    def post (self, request, *args, **kwargs):
        user_post = request.POST['user']
        password_post = request.POST['password']
       
        user_session = authenticate(username = user_post, password = password_post)
      
        if user_session is not None:
            login_django(
                request, user_session
            )
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('Dashboard:Dashboard')
        else: 
            self.message = 'Usuario o contraseña incorrecto'
        
        return render(request, self.templates, self.get_context())

    def get_context(self):
        return{
           'error': self.message
        }
    

venvfinal/final/Registro/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from Registro.forms import RegisterBusinessForm

class RegistrateView(FormView):
    template_name = 'Login/registro-usuarios.html'

# GET
    def get(self, request, *args, **kwargs):
            form = RegisterBusinessForm(request.GET or None)    
            context = {
                'form_get' : form
            }
            return render(request, self.template_name, context)

    # POST
    def post(self, request, *args, **kwargs):
        form = RegisterBusinessForm(request.POST or None)

        if form.is_valid():
            self.object = form.save(commit = False)
            self.object.set_password(self.object.password)
            self.object.save()
        return redirect('Login:Login')

venvfinal/final/templates/Dashboard/Dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h1>hola dash</h1>
    <br>
    <h1>Usuario {{request.user.username}}</h1>
<br>
<h1>Email {{request.user.email}}</h1>
<br>
    <a href="{% url 'logout'%}"> Cerrar sesion</a>
</body>
</html>

venvfinal/final/templates/Landing/Landing.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>landing</title>
  </head>
  <body>
      <center>
        <div>
            <img src="https://images.unsplash.com/photo-1578104033152-58c33c7e3cd2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80" style = "width: 100px;"  alt="" class="rounded-circle">
        </div>
      </center>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                <img src="https://images.unsplash.com/photo-1544077960-604201fe74bc?ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://images.unsplash.com/photo-1544411047-c491e34a24e0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjExMDk0fQ&auto=format&fit=crop&w=1050&q=80" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://images.unsplash.com/photo-1479502806991-251c94be6b15?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjF9&auto=format&fit=crop&w=1050&q=80" class="d-block w-100" alt="...">
            </div>
        </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

venvfinal/final/templates/Login/Login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login</title>
</head>
<body background="https://images.unsplash.com/photo-1542876974-aa06c4f5c6c4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjIyMjh9&auto=format&fit=crop&w=562&q=80">
    <br>
    <br>
    <br>
    <br>
    <center>
        <div class="border border-dark"  style="width: 300px; height: 500px; text-align: center;">
            <br>
            
            <img src="https://images.unsplash.com/photo-1578104033152-58c33c7e3cd2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80" style = "width: 100px;"  alt="" class="rounded-circle">
            <br>
            <br>
            <form action="" method="POST">
                {%csrf_token%}
                <div class="form-group">
                    <label for="email1">Correo</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" required name = "user">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Contraseña</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required name = "password">
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Recuerdame</label>
                </div>
                    <br>
                    <br>
                    <button type="submit" class="btn btn-primary">Iniciar Sesion
                    </button>
                    <br>
                    <br>
            
                
                    {% if error %}
                    <div class = "alert alert-warning" role="alert">
                        {%if error %}
                            {{error}}
                        {% endif%}
                    </div>
                    {% endif%}
                    <span>
                    </span>
                    
            </form>
            <a href= "{% url 'Registro:Registro'%}">Registrate</a>
        </div>  
    </center>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

venvfinal/final/templates/Login/registro-usuarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login</title>
</head>
<body background="https://images.unsplash.com/photo-1542876974-aa06c4f5c6c4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjIyMjh9&auto=format&fit=crop&w=562&q=80">
    <br>
    <br>
    <br>
    <br>
    <center>
        <div class="border border-dark"  style="width: 300px; height: 500px; text-align: center;">
            <br>
            
            <img src="https://images.unsplash.com/photo-1578104033152-58c33c7e3cd2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80" style = "width: 100px;"  alt="" class="rounded-circle">
            <br>
            <br>
            <form action="" method="POST">
                {%csrf_token%}
                <br>
                {% if form_get.username.value %}
                {{ form_get.username }}
                {% else %}
                {{ form_get.username }}
                {% endif %}
                <br>
                {% if form_get.first_name.value %}
                {{ form_get.first_name }}
                {% else %}
                {{ form_get.first_name }}
                {% endif %}
                <br>
                {% if form_get.last_name.value %}
                {{ form_get.last_name }}
                {% else %}
                {{ form_get.last_name }}
                {% endif %}
                <br>
                {% if form_get.password.value %}
                {{ form_get.password }}
                {% else %}
                {{ form_get.password }}
                {% endif %}
                <br>
                {% if form_get.email.value %}
                {{ form_get.email }}
                {% else %}
                {{ form_get.email }}
                {% endif %}
                <br>
                <button type="submit" class="btn btn-primary">Registrate
                </button>
            </form>
            
        </div>  
    </center>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>